def drawstickman(life):
    if life == 6:
        print("  /--\  ")
        print("  |   |")
        print("  |   ")
        print("  |   ")
        print("  |   ")
        print("____")
    elif life == 5:
        print("  /--\  ")
        print("  |   |")
        print("  |   O")
        print("  |  ")
        print("  |  ")
        print("____")
    elif life == 4:
        print("  /--\  ")
        print("  |   |")
        print("  |   O")
        print("  |   | ")
        print("  |   ")
        print("____")        
    elif life == 3:
        print("  /--\  ")
        print("  |   |")
        print("  |   O")
        print("  |  /| ")
        print("  |   ")
        print("____")
    elif life == 2:
        print("  /--\  ")
        print("  |   |")
        print("  |   O")
        print("  |  /|\ ")
        print("  |   ")
        print("____")
    elif life == 1:
        print("  /--\  ")
        print("  |   |")
        print("  |   O")
        print("  |  /|\ ")
        print("  |  / ")
        print("____")
    else:
        print("  /--\  ")
        print("  |   |")
        print("  |   O")
        print("  |  /|\ ")
        print("  |  /\ ")
        print("____")
